Fix handling of aggregate literals with only a right-hand comparison term (Issue #311)
alpha-asp/Alpha pull request #318
Opened 2021-12-14 18:36 UTC by madmike200590

Fixed in `AggregateOperatorNormalization`:
Aggregates of form `#aggr{...} OP TERM` are rewritten into `TERM inv(OP) #aggr{...}` and then processed as before.
`inv(OP)` refers to the inverse operator, i.e. `inv(<) = >=` etc. For operators `=` and `!=` no inverse operator is used, i.e. rewritten form is `TERM OP #aggr{...}`.

Closes #311

2021-12-14 21:18 UTC, lorenzleutgeb commented on alpha-core/src/test/java/at/ac/tuwien/kr/alpha/core/solver/AggregatesTest.java
> +		String program = "p(1)." +
@AntoniusW regarding #301: Here, IMO [JEP-378: Text Blocks](https://openjdk.java.net/jeps/378) would make this look prettier.

2021-12-14 21:31 UTC, lorenzleutgeb approved these changes
LGTM, minor remarks.

2021-12-14 21:31 UTC, lorenzleutgeb commented on alpha-core/src/main/java/at/ac/tuwien/kr/alpha/core/programs/transformation/aggregates/AggregateOperatorNormalization.java
> +			}
The difference in the second argument seems to be the only difference between the two branches. You could make that more explicit by doing:

```suggestion
			var flippedUpperBoundOperator = EQ.equals(operator) || NE.equals(operator) ? atom.getUpperBoundOperator() : atom.getUpperBoundOperator().negate();
                        // "flip" right-hand operator and term to left-hand ones.
			AggregateLiteral flipped = Atoms.newAggregateAtom(
					flippedUpperBoundOperator, 
					atom.getUpperBoundTerm(), 
					atom.getAggregateFunction(),
					atom.getAggregateElements()).toLiteral(!lit.isNegated());
```

2021-12-14 22:57 UTC, AntoniusW commented
> Fixed in `AggregateOperatorNormalization`: Aggregates of form `#aggr{...} OP TERM` are rewritten into `TERM inv(OP) #aggr{...}` and then processed as before. `inv(OP)` refers to the inverse operator, i.e. `inv(<) = >=` etc. For operators `=` and `!=` no inverse operator is used, i.e. rewritten form is `TERM OP #aggr{...}`.

Uhm, I beg to disagree:
`#agg {..} > 2` should be equal to `2 < #agg {..}`, i.e., what is needed here is flipping of operators, not negation.

Consider for example `X < Y` which is flipped `Y > X` and not `Y >= X`, to see that consider the case with `X=2,Y=2` and we have `2 < 2` is false as is `2 > 2` while `2 >= 2` becomes true. The unit tests currently do not consider such a case and hence cannot show that the implementation is bugged at the moment.

Please change that.

2021-12-15 07:09 UTC, rtaupe requested changes
Please address @AntoniusW's comment.

2021-12-15 16:29 UTC, madmike200590 commented
> > Fixed in `AggregateOperatorNormalization`: Aggregates of form `#aggr{...} OP TERM` are rewritten into `TERM inv(OP) #aggr{...}` and then processed as before. `inv(OP)` refers to the inverse operator, i.e. `inv(<) = >=` etc. For operators `=` and `!=` no inverse operator is used, i.e. rewritten form is `TERM OP #aggr{...}`.
> 
> Uhm, I beg to disagree: `#agg {..} > 2` should be equal to `2 < #agg {..}`, i.e., what is needed here is flipping of operators, not negation.
> 
> Consider for example `X < Y` which is flipped `Y > X` and not `Y >= X`, to see that consider the case with `X=2,Y=2` and we have `2 < 2` is false as is `2 > 2` while `2 >= 2` becomes true. The unit tests currently do not consider such a case and hence cannot show that the implementation is bugged at the moment.
> 
> Please change that.

Thanks for catching this! Since the actual rewriting in `AggregateOperatorNormalization` uses operator negation in quite a few places, I mentally tripped myself up here :sweat_smile: 

This should now be fixed.

2021-12-15 18:08 UTC, rtaupe approved these changes
Thanks for fixing this! 😃

2021-12-15 18:08 UTC, merged